### ISSUE TITLE
Seconds vs. milliseconds in the example

### ISSUE THREAD

**Issue by dteleguin** [oauth-wg/oauth-transaction-tokens#114]
In [5.2.4](https://www.ietf.org/archive/id/draft-ietf-oauth-transaction-tokens-03.html#section-5.2.4):

```
{
  "iat": "1686536226000",
  "aud": "trust-domain.example",
  "exp": "1686536526000",
  ...
}
```

The `iat` and `exp` claims are strings expressed in milliseconds. According to RFC 7519 [4.1](https://www.rfc-editor.org/rfc/rfc7519#section-4.1), those should be numerics and expressed in seconds.

**Comment by gffletch** [comment]
Thank you! Will update the examples to be correct.
