### ISSUE TITLE
Clarify Transaction Token Context

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-transaction-tokens#127]
In section 2.2.1 the context that may be included in a transaction token includes "The external authorization token (e.g., the OAuth access token)". To ensure this is not interpreted to mean that an access token is included in a transaction token, I would suggest the following additions, in line with section 9.3 in Security Considerations:

"A reference to the external authorization token (e.g., the OAuth access token), including scopes or claims included in the authorization token, but not the unmodified authorization token (see Security Considerations, Section 9.3)"

**Comment by gffletch** [comment]
Pieter, in that section of the spec we are describing what needs to be sent to the Transaction token service, I think in that case the full access token should be passed. However, when generating the request context, we want to ensure that the full access token is not included. Did I get my spec sections wrong?

**Comment by gffletch** [comment]
Maybe instead we shouldn't say "This context MAY include:" but rather ... "The information provided to the Txn-Token Service MAY include" to not confuse readers who might think this data should be included in the request context.

**Comment by PieterKas** [comment]
Agreed - I missed that this was for initial token creation. I did create a PR with your suggested text.

**Comment by gffletch** [comment]
PR approved
