### ISSUE TITLE
rctx MUST

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-transaction-tokens#132]
Section 7.1 makes the inclusion of an rctx value mandatory (MUST). 

1. Should this be a MUST, or could it be omitted if no additional context is passed
2. If no additional context is passed, should we specify that it is included, but with a null value?

@gffletch @tulshi

**Comment by gffletch** [comment]
I think it should be a MUST because the requesting workload identity is part of the `rctx`. Maybe we could clarify that only specifying that value is ok. Is there a reason that the requesting workload should NOT be part of the TraT?

**Comment by PieterKas** [comment]
Latest drafts show rctx as optional....
