### ISSUE TITLE
Clarify why the "aud" claim remains unchanged

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-transaction-tokens#134]
Good practice is to explain why something is a MUST. 

Suggestion:

From: The value of the aud claim MUST remain unchanged in a replacement Txn-Token.

To: The value of the aud claim MUST remain unchanged in a replacement Txn-Token to prevent the Txn-Token from being accepted outside it's current Trust Domain.

Alternatively, we cann add security considerations for the draft as well.

**Comment by gffletch** [comment]
I'm good with that text.

**Comment by tulshi** [comment]
I think the current PR is making the change in the wrong place (unless I'm horribly mistaken)
