### ISSUE TITLE
It would be good to show how, in a replacement txn-token, the identity of the previous sub_id is preserved. The replacement token may have a new sub_id that represent the workload that requested the replacement token.

### ISSUE THREAD

**Issue by tulshi** [oauth-wg/oauth-transaction-tokens#44]
It would be good to show how, in a replacement txn-token, the identity of the previous sub_id is preserved. The replacement token may have a new sub_id that represent the workload that requested the replacement token.

_Originally posted by @PieterKas in https://github.com/SGNL-ai/transaction-tokens/issues/30#issuecomment-1745613590_

**Comment by gffletch** [comment]
Can we close this since it was addressed in PR #71?
