### ISSUE TITLE
Should the azd claim be mandatory or optional

### ISSUE THREAD

**Issue by gffletch** [oauth-wg/oauth-transaction-tokens#52]
I’m wondering if we should move the `azd` claim to the Optional section as there may be some cases where it’s not required. I’d hate for systems to have to process and empty `azd` object. We might be able to leave it in the MUST category if we add text that says if there are no `azd` claims then the object MUST NOT be included in the transaction token.

**Comment by tulshi** [comment]
Since we no longer have an optional and mandatory section, I shall close this issue. Please reopen if you think this needs to be addressed.
