### ISSUE TITLE
Do we still need replacement transaction tokens.

### ISSUE THREAD

**Issue by PieterKas** [oauth-wg/oauth-transaction-tokens#69]
We need to clarify the use case for replacement transaction token and whether we still have it. We included it in the past to preserve call chain information, but it is unclear if we still should address this in the transaction token.

**Comment by PieterKas** [comment]
Conversation: https://hackmd.io/@rpc-sec-wg/Hk0ggi5ca

**Comment by gffletch** [comment]
@PieterKas do we still want to keep this issue open? Or are we good with the latest text around replacement transaction tokens?

**Comment by tulshi** [comment]
@PieterKas you can re-open this if you think we should discuss this.
