### ISSUE TITLE
Move 'aud' requirement in Trust Domain away from 'Terminology' section

### ISSUE THREAD

**Issue by tulshi** [oauth-wg/oauth-transaction-tokens#76]
Point from Yaron's [feedback email](https://mailarchive.ietf.org/arch/msg/oauth/qPxczdlhrkWbAu6eD8VmMmqRZj8/)

**Comment by gffletch** [comment]
From Yaron:

> 4: the terminology section is not a good place for normative language, specifically around the "aud" claim.

**Comment by gffletch** [comment]
Great point. I think I can move the key aspects into section 5.2
