### ISSUE TITLE
`txn` value should be optional

### ISSUE THREAD

**Issue by tulshi** [oauth-wg/oauth-transaction-tokens#77]
From Yaron's [feedback email](https://mailarchive.ietf.org/arch/msg/oauth/qPxczdlhrkWbAu6eD8VmMmqRZj8/)

**Comment by gffletch** [comment]
I'm curious to the use cases? I'd prefer a way to make the `txn` claim REQUIRED and allow an organization to provide it's own value in that context. Maybe we could go with RECOMMENDED? This is one of those cases where people who know what they are doing can potentially remove it or possibly provide a "N_A" value and it will be fine. However, if it's OPTIONAL most developers will not specify the value and then they will lose a lot of value from the Transaction Token.

**Comment by yaronf** [comment]
No specific use cases, it's just that we're assuming that an organization can easily integrate its (preexisting) transaction ID-issuing service with this one. Sometimes it can, sometimes it can't.

I'm good with RECOMMENDED.

**Comment by gffletch** [comment]
@yaronf please review PR #101 which addresses this issue
