### ISSUE TITLE
Possible confusion in IANA registry section

### ISSUE THREAD

**Issue by tulshi** [oauth-wg/oauth-transaction-tokens#84]
Yaron's [feedback email](https://mailarchive.ietf.org/arch/msg/oauth/qPxczdlhrkWbAu6eD8VmMmqRZj8/) states that:
"11.1: I think there is some confusion here. It is possibly useful to define this value (if we want to embed txn tokens within access tokens). But the "typ" header is a whole different thing, it needs to be a media type. See https://datatracker.ietf.org/doc/html/rfc8725#name-use-explicit-typing"

I'm not completely sure about this, so tracking this item

**Comment by bc-pi** [comment]
https://hackmd.io/@rpc-sec-wg/SyAb2pxI6 from a while back had "https://www.ietf.org/archive/id/draft-ietf-oauth-transaction-tokens-00.html#name-iana-considerations Registration requests are off or missing or …."
